image: dtuwindenergy/hydesign:latest

# ===== TEST hydesign debian=====
test_hydesign:
  stage: 
    test
  script:
  - pip install -e .[test]
  - python -m pytest
  tags:
  - debian

# ===== TEST hydesign windows=====
test_hydesign_windows:
  stage:
    test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  script:
  - conda init powershell
  - "if (test-path $PROFILE.CurrentUserAllHosts) { & $PROFILE.CurrentUserAllHosts}"
  - conda activate hydesign
  - pip install -e . --no-deps
  - pytest --cov-report term-missing:skip-covered --cov=hydesign --cov-config .coveragerc
  tags:
  - ANMH_old

# ===== DEPLOY hydesign docs=====
pages:
  stage:  
    deploy
  script:  
  - pip install -e .[docs] --upgrade
  - cd docs; make html
  - cd ../; mv docs/build/html public/
  artifacts:
    paths:
    - public
  only: 
  - /^test_docdeploy.*/ 
  - main
  tags: 
  - debian
