image: dtuwindenergy/hydesign:latest

# ===== TEST hydesign debian=====
test_hydesign:
  stage: 
    test
  script:
  - source activate py37
  - pip install -e .
  - pytest
  tags:
  - debian

# ===== TEST hydesign windows=====
test_hydesign_windows:
  stage:
    test
  script:
  - conda init powershell
  - "if (test-path $PROFILE.CurrentUserAllHosts) { & $PROFILE.CurrentUserAllHosts}"
  - conda activate hydesign
  - pip install -e . --no-deps
  - pytest --cov-report term-missing:skip-covered --cov=hydesign --cov-config .coveragerc
  tags:
  - ANMH_old
